---
- name: Install and Configure Nginx on EC2 Nodes
  hosts: ec2_nodes
  become: true

  tasks:

    - name: Update apt cache and Install Nginx
      apt:
        update_cache: yes
        name: nginx
        state: present

    # - name: Install nginx
    #   apt:
    #     name: nginx
    #     state: present

    - name: Copy custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: true
